name: Check static types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install --use-pep517 -e '.[tests]'
          pip install --upgrade mypy

      - name: Run mypy
        run: mypy --show-traceback src/
